// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "go-rest-security": Action Resource Client
//
// Command:
// $ goagen
// --design=github.com/mrcaelumn/Go-REST-API-Security/api/design
// --out=$(GOPATH)/src/github.com/mrcaelumn/Go-REST-API-Security/api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// GetTokenActionPath computes a request path to the getToken action of Action.
func GetTokenActionPath() string {

	return fmt.Sprintf("/gorestsecurity/getToken")
}

// GetTokenAction makes a request to the getToken action endpoint of the Action resource
func (c *Client) GetTokenAction(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewGetTokenActionRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewGetTokenActionRequest create the request corresponding to the getToken action endpoint of the Action resource.
func (c *Client) NewGetTokenActionRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}

// RequestActionPath computes a request path to the request action of Action.
func RequestActionPath() string {

	return fmt.Sprintf("/gorestsecurity/request")
}

// RequestAction makes a request to the request action endpoint of the Action resource
func (c *Client) RequestAction(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewRequestActionRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewRequestActionRequest create the request corresponding to the request action endpoint of the Action resource.
func (c *Client) NewRequestActionRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
