// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "go-rest-security": version Resource Client
//
// Command:
// $ goagen
// --design=github.com/mrcaelumn/Go-REST-API-Security/api/design
// --out=$(GOPATH)/src/github.com/mrcaelumn/Go-REST-API-Security/api
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// VersionVersionPath computes a request path to the version action of version.
func VersionVersionPath() string {

	return fmt.Sprintf("/gorestsecurity/version")
}

// VersionVersion makes a request to the version action endpoint of the version resource
func (c *Client) VersionVersion(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewVersionVersionRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewVersionVersionRequest create the request corresponding to the version action endpoint of the version resource.
func (c *Client) NewVersionVersionRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "https"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
