// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "go-rest-security": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/mrcaelumn/Go-REST-API-Security/api/design
// --out=$(GOPATH)/src/github.com/mrcaelumn/Go-REST-API-Security/api
// --version=v1.3.1

package app
