// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "go-rest-security": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/mrcaelumn/Go-REST-API-Security/api/design
// --out=$(GOPATH)/src/github.com/mrcaelumn/Go-REST-API-Security/api
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// Gorestsecurity-Error media type (default view)
//
// Identifier: application/vnd.gorestsecurity-error+json; view=default
type GorestsecurityError struct {
	// Message ID
	Code string `form:"code" json:"code" yaml:"code" xml:"code"`
	// Localized message
	Msg string `form:"msg" json:"msg" yaml:"msg" xml:"msg"`
}

// Validate validates the GorestsecurityError media type instance.
func (mt *GorestsecurityError) Validate() (err error) {
	if mt.Code == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "code"))
	}
	if mt.Msg == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "msg"))
	}
	return
}

// Gorestsecurity-Version media type (default view)
//
// Identifier: application/vnd.gorestsecurity-version+json; view=default
type GorestsecurityVersion struct {
	// Git commit hash
	Git *string `form:"git,omitempty" json:"git,omitempty" yaml:"git,omitempty" xml:"git,omitempty"`
	// Application version
	Version string `form:"version" json:"version" yaml:"version" xml:"version"`
}

// Validate validates the GorestsecurityVersion media type instance.
func (mt *GorestsecurityVersion) Validate() (err error) {
	if mt.Version == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "version"))
	}
	return
}
